
import nodemailer from "nodemailer";
import { simpleParser } from "mailparser";
import { extractLoadInfo, generateLoadSummary } from "./openai";
import { storage } from "./storage";

let transporter: nodemailer.Transporter;

export function initializeEmailClient() {
  if (!transporter) {
    // Support both Gmail and Outlook
    const emailProvider = process.env.EMAIL_PROVIDER || "gmail";
    
    let smtpConfig;
    if (emailProvider === "outlook") {
      smtpConfig = {
        host: "smtp-mail.outlook.com",
        port: 587,
        secure: false,
        auth: {
          user: process.env.OUTLOOK_EMAIL || process.env.EMAIL_USER,
          pass: process.env.OUTLOOK_PASSWORD || process.env.EMAIL_PASS,
        },
      };
    } else {
      // Gmail configuration
      smtpConfig = {
        host: "smtp.gmail.com", 
        port: 587,
        secure: false,
        auth: {
          user: process.env.GMAIL_EMAIL || process.env.EMAIL_USER,
          pass: process.env.GMAIL_APP_PASSWORD || process.env.EMAIL_PASS,
        },
      };
    }

    transporter = nodemailer.createTransport(smtpConfig);
  }
  return transporter;
}

export function getEmailClient() {
  if (!transporter) {
    throw new Error('Email client not initialized. Call initializeEmailClient() first.');
  }
  return transporter;
}

interface LoadNotificationData {
  loadId: string;
  customerName: string;
  customerPhone: string;
  route: string;
  cargoType: string;
  weight: string;
  truckType: string;
  deadline?: string;
  summary: string;
}

export async function sendOwnerNotification(
  ownerEmail: string, 
  loadData: LoadNotificationData,
  approveUrl: string,
  rejectUrl: string
): Promise<void> {
  try {
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background-color: #2563EB; color: white; padding: 20px; text-align: center;">
          <h1 style="margin: 0;">🚛 TruckFlow AI - New Load Request</h1>
          <p style="margin: 5px 0 0 0;">Load ID: ${loadData.loadId}</p>
        </div>
        
        <div style="padding: 20px; background-color: #f8f9fa;">
          <h2 style="color: #1f2937; margin-top: 0;">Load Details</h2>
          
          <div style="background-color: white; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="color: #374151; margin-top: 0;">Customer Information</h3>
            <p><strong>Name:</strong> ${loadData.customerName}</p>
            <p><strong>Phone:</strong> ${loadData.customerPhone}</p>
          </div>
          
          <div style="background-color: white; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="color: #374151; margin-top: 0;">Route & Cargo</h3>
            <p><strong>Route:</strong> ${loadData.route}</p>
            <p><strong>Cargo:</strong> ${loadData.cargoType}</p>
            <p><strong>Weight:</strong> ${loadData.weight}</p>
            <p><strong>Equipment:</strong> ${loadData.truckType}</p>
            ${loadData.deadline ? `<p><strong>Deadline:</strong> ${loadData.deadline}</p>` : ''}
          </div>
          
          <div style="background-color: white; padding: 15px; border-radius: 8px; margin-bottom: 30px;">
            <h3 style="color: #374151; margin-top: 0;">AI Summary</h3>
            <p style="line-height: 1.6;">${loadData.summary}</p>
          </div>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="${approveUrl}" 
               style="background-color: #16A34A; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-right: 10px; display: inline-block;">
              ✅ Approve Load
            </a>
            <a href="${rejectUrl}" 
               style="background-color: #DC2626; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              ❌ Reject Load
            </a>
          </div>
          
          <div style="text-align: center; color: #6b7280; font-size: 14px; margin-top: 30px;">
            <p>This notification was automatically generated by TruckFlow AI</p>
            <p>Processed at: ${new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>
    `;

    const mailOptions = {
      from: process.env.EMAIL_USER || "noreply@truckflowai.com",
      to: ownerEmail,
      subject: `🚛 New Load Request - ${loadData.loadId}`,
      html: emailHtml,
    };

    await getEmailClient().sendMail(mailOptions);
    console.log(`Notification email sent to ${ownerEmail} for load ${loadData.loadId}`);
  } catch (error) {
    console.error("Error sending email notification:", error);
    throw new Error("Failed to send email notification: " + (error as Error).message);
  }
}

export async function sendOwnerSMS(
  phoneNumber: string,
  loadId: string,
  customerName: string,
  route: string
): Promise<void> {
  // In a real implementation, this would integrate with Twilio SMS
  // For now, we'll just log the SMS that would be sent
  console.log(`SMS would be sent to ${phoneNumber}:`);
  console.log(`🚛 TruckFlow AI: New load request ${loadId} from ${customerName}. Route: ${route}. Check email for details.`);
}

// Track processed emails to prevent duplicates
const processedEmails = new Set<string>();

// Generate a unique hash for email content to prevent duplicates
function generateEmailHash(emailContent: string, fromAddress: string, timestamp: string): string {
  const crypto = require('crypto');
  const hashInput = `${fromAddress}:${emailContent.slice(0, 500)}:${timestamp}`;
  return crypto.createHash('md5').update(hashInput).digest('hex');
}

// Extract and parse PDF content using OpenAI text processing (pure AI approach)
export async function extractAndParsePDF(pdfBuffer: Buffer, filename: string): Promise<any> {
  try {
    // For this pure OpenAI approach, we'll treat the buffer as text content
    // In a real implementation, you'd use a PDF text extraction library here
    // For now, we'll convert the buffer to string for OpenAI processing
    const pdfText = pdfBuffer.toString('utf8');
    console.log(`Processing PDF ${filename} with OpenAI text analysis (size: ${pdfBuffer.length} bytes)`);
    
    // Use OpenAI to directly process the PDF text content and extract structured load information
    const { extractLoadInfoFromPDF } = await import('./openai');
    const extractedData = await extractLoadInfoFromPDF(pdfText, filename);
    
    if (!extractedData) {
      console.log(`No structured data could be extracted from PDF: ${filename}`);
      return null;
    }

    console.log(`OpenAI successfully parsed PDF ${filename}:`, JSON.stringify(extractedData, null, 2));
    
    return {
      rawText: pdfText,
      extractedData,
      filename
    };
  } catch (error) {
    console.error(`Error processing PDF ${filename} with OpenAI:`, error);
    return null;
  }
}

// Process PDF attachments using OpenAI for structured data extraction
async function processPDFAttachments(parsed: any): Promise<{
  combinedText: string;
  extractedDataList: any[];
  pdfCount: number;
}> {
  let combinedText = '';
  const extractedDataList: any[] = [];
  let pdfCount = 0;
  
  if (parsed.attachments && parsed.attachments.length > 0) {
    console.log(`Found ${parsed.attachments.length} attachments`);
    
    for (const attachment of parsed.attachments) {
      console.log(`Processing attachment: ${attachment.filename}, type: ${attachment.contentType}`);
      
      // Only process PDF attachments
      if (attachment.contentType === 'application/pdf' || 
          (attachment.filename && attachment.filename.toLowerCase().endsWith('.pdf'))) {
        
        console.log(`Processing PDF attachment with OpenAI: ${attachment.filename}`);
        const pdfData = await extractAndParsePDF(attachment.content, attachment.filename);
        
        if (pdfData) {
          pdfCount++;
          combinedText += `\n\n=== PDF Content from ${attachment.filename} ===\n${pdfData.rawText}\n=== End PDF Content ===\n`;
          extractedDataList.push({
            filename: attachment.filename,
            extractedData: pdfData.extractedData,
            rawText: pdfData.rawText
          });
        }
      }
    }
  }
  
  return {
    combinedText,
    extractedDataList,
    pdfCount
  };
}

// Email monitoring functionality
export async function processIncomingEmail(emailContent: string, fromAddress: string, messageId?: string): Promise<void> {
  try {
    console.log(`Processing incoming email from ${fromAddress}`);
    
    // Parse email content
    const parsed = await simpleParser(emailContent);
    let emailText =
      typeof parsed.text === 'string' ? parsed.text :
      typeof parsed.html === 'string' ? parsed.html.replace(/<[^>]*>/g, '') :
      emailContent?.toString() || '';
    
    // Process PDF attachments using OpenAI
    const pdfResults = await processPDFAttachments(parsed);
    if (pdfResults.combinedText) {
      emailText = emailText + pdfResults.combinedText;
      console.log(`Combined email text with ${pdfResults.pdfCount} PDF(s) (total length: ${emailText.length})`);
    }
    
    // Create unique identifier for this email
    const emailHash = messageId || generateEmailHash(emailText, fromAddress, parsed.date?.toISOString() || new Date().toISOString());
    
    // Check if we've already processed this email
    if (processedEmails.has(emailHash)) {
      console.log(`Email already processed (hash: ${emailHash}), skipping...`);
      return;
    }
    
    // Add to processed emails set
    processedEmails.add(emailHash);
    console.log(`Processing new email (hash: ${emailHash})`);
    
    // Check if email text is meaningful for load requests
    if (!emailText || emailText.trim().length < 20) {
      console.log('Email content too short or empty, skipping load request creation');
      return;
    }
    
    console.log(`Final email text for processing: ${emailText.slice(0, 200)}...`);
    
    // Combine PDF extracted data with email analysis
    let extractedData;
    if (pdfResults.extractedDataList.length > 0) {
      // Use PDF extracted data as primary source, supplement with email analysis
      console.log(`Found ${pdfResults.extractedDataList.length} PDF(s) with extracted data`);
      extractedData = pdfResults.extractedDataList[0].extractedData; // Use first PDF as primary
      
      // Enhance with email analysis if needed
      const emailExtractedData = await extractLoadInfo(emailText);
      
      // Merge data, prioritizing PDF data but filling gaps with email data
      extractedData = {
        ...emailExtractedData,
        ...extractedData, // PDF data takes precedence
        // Combine notes from both sources
        additionalNotes: [
          extractedData.additionalNotes,
          emailExtractedData.additionalNotes
        ].filter(Boolean).join('; ')
      };
      
      console.log(`Combined PDF and email extracted data:`, JSON.stringify(extractedData, null, 2));
    } else {
      // No PDFs found, use standard email analysis
      extractedData = await extractLoadInfo(emailText);
      console.log(`Email-only extracted load information:`, JSON.stringify(extractedData, null, 2));
    }
    
    // Only create load request if we have meaningful pickup/delivery information
    if (!extractedData.pickupLocation && !extractedData.deliveryLocation) {
      console.log('No meaningful pickup/delivery information found, skipping load request creation');
      return;
    }
    
    // Generate unique load ID using the email hash
    const loadId = `EML-${new Date().getFullYear()}-${emailHash.slice(0, 4).toUpperCase()}`;
    
    // Check if load request with this ID already exists
    try {
      const existingLoad = await storage.getLoadRequestByLoadId(loadId);
      if (existingLoad) {
        console.log(`Load request ${loadId} already exists, skipping duplicate creation`);
        return;
      }
    } catch (error) {
      // If getLoadRequestByLoadId doesn't exist or fails, continue with creation
    }
    
    // Process additional locations if they exist (for email)
    let pickupLocationsJson = null;
    let deliveryLocationsJson = null;
    
    if (extractedData.additionalPickups && extractedData.additionalPickups.length > 0) {
      pickupLocationsJson = JSON.stringify(extractedData.additionalPickups.map((pickup, index) => ({
        id: `pickup-${index + 1}`,
        location: pickup.location,
        address: pickup.address || "Not specified",
        contactName: pickup.contactName,
        contactPhone: pickup.contactPhone,
        scheduledTime: pickup.scheduledTime,
        instructions: pickup.instructions
      })));
    }
    
    if (extractedData.additionalDeliveries && extractedData.additionalDeliveries.length > 0) {
      deliveryLocationsJson = JSON.stringify(extractedData.additionalDeliveries.map((delivery, index) => ({
        id: `delivery-${index + 1}`,
        location: delivery.location,
        address: delivery.address || "Not specified",
        contactName: delivery.contactName,
        contactPhone: delivery.contactPhone,
        scheduledTime: delivery.scheduledTime,
        instructions: delivery.instructions
      })));
    }

    // Create load request from email
    const loadRequest = await storage.createLoadRequest({
      loadId,
      customerName: extractedData.customerName || "Email Customer",
      customerPhone: extractedData.customerPhone || "Not provided",
      customerEmail: fromAddress, // Store sender email as customer email
      pickupLocation: extractedData.pickupLocation || "Not specified",
      pickupAddress: extractedData.pickupAddress || "Not specified",
      pickupContactName: extractedData.pickupContactName,
      pickupContactPhone: extractedData.pickupContactPhone,
      deliveryLocation: extractedData.deliveryLocation || "Not specified",
      deliveryAddress: extractedData.deliveryAddress || "Not specified",
      cargoType: extractedData.cargoType || "Not specified",
      weight: extractedData.weight || "Not specified",
      truckType: extractedData.truckType || "Not specified",
      pickupTime: extractedData.pickupTime,
      deliveryTime: extractedData.deliveryTime,
      deadline: extractedData.deadline,
      additionalNotes: extractedData.additionalNotes,
      pickupLocations: pickupLocationsJson,
      deliveryLocations: deliveryLocationsJson,
      status: "pending",
      transcription: `Email from: ${fromAddress}\nMessage ID: ${emailHash}\nPDF Attachments: ${pdfResults.pdfCount}\nProcessed with OpenAI: ${pdfResults.extractedDataList.length > 0 ? 'Yes' : 'No'}\n\n${emailText}`,
      extractedData: JSON.stringify(extractedData),
      notificationSent: false,
    });

    // Save to Google Sheets (will log error if not configured)
    try {
      const { saveLoadToGoogleSheets } = await import('./googleSheets');
      await saveLoadToGoogleSheets(loadRequest);
    } catch (error) {
      console.log("Google Sheets not configured, skipping...");
    }

    // Generate summary and send notification
    const summary = await generateLoadSummary(extractedData);
    const baseUrl = process.env.BASE_URL || "http://localhost:5000";
    const approveUrl = `${baseUrl}/api/load-requests/${loadRequest.id}/approve`;
    const rejectUrl = `${baseUrl}/api/load-requests/${loadRequest.id}/reject`;

    await sendOwnerNotification(
      process.env.OWNER_EMAIL || "rk3110@nyu.edu",
      {
        loadId: loadRequest.loadId,
        customerName: extractedData.customerName || "Email Customer",
        customerPhone: extractedData.customerPhone || fromAddress,
        route: `${extractedData.pickupLocation} → ${extractedData.deliveryLocation}`,
        cargoType: extractedData.cargoType,
        weight: extractedData.weight,
        truckType: extractedData.truckType,
        deadline: extractedData.deadline,
        summary,
      },
      approveUrl,
      rejectUrl
    );

    console.log(`Email processed successfully: Load ${loadId} created`);
  } catch (error) {
    console.error("Error processing incoming email:", error);
  }
}

// IMAP connection for monitoring emails
import Imap from 'imap';

let imapClient: Imap;

export function initializeEmailMonitoring() {
  const emailProvider = process.env.EMAIL_PROVIDER || "gmail";
  console.log(`Using ${emailProvider} for email monitoring`);
  
  let imapConfig;
  if (emailProvider === "outlook") {
    console.log('Using Outlook for email monitoring');
    imapConfig = {
      user: process.env.OUTLOOK_EMAIL || process.env.EMAIL_USER,
      password: process.env.OUTLOOK_PASSWORD || process.env.EMAIL_PASS,
      host: 'outlook.office365.com',
      port: 993,
      tls: true,
      tlsOptions: { rejectUnauthorized: false }
    };
  } else {
    // Gmail configuration
    console.log('Using Gmail for email monitoring');
    imapConfig = {
      user: process.env.EMAIL_USER,
      password: process.env.EMAIL_PASS,
      host: 'imap.gmail.com',
      port: 993,
      tls: true,
      tlsOptions: { rejectUnauthorized: false }
    };
  }
  console.log('IMAP configuration:', imapConfig);

  if (!imapConfig.user || !imapConfig.password) {
    console.log('Email monitoring disabled - credentials not configured');
    return;
  }

  imapClient = new Imap(imapConfig);

  imapClient.once('ready', () => {
    console.log('Email monitoring connected');
    
    // Monitor inbox for new emails
    imapClient.openBox('INBOX', false, (err) => {
      if (err) {
        console.error('Error opening inbox:', err);
        return;
      }
      
      // Listen for new emails
      imapClient.on('mail', (numNewMsgs) => {
        console.log(`${numNewMsgs} new email(s) received`);
        fetchNewEmails();
      });
    });
  });
  console.log('Email monitoring connected');
  imapClient.once('error', (err: Error) => {
    console.error('IMAP connection error:', err);
  });

  imapClient.once('end', () => {
    console.log('Email monitoring connection ended');
  });

  imapClient.connect();
}

function fetchNewEmails() {
  // Search for unread emails
  imapClient.search(['UNSEEN'], (err, results) => {
    if (err) {
      console.error('Error searching emails:', err);
      return;
    }

    if (results.length === 0) {
      return;
    }

    const fetch = imapClient.fetch(results, { 
      bodies: '',  // Get full email body including attachments
      markSeen: true,
      envelope: true,
      struct: true
    });

    fetch.on('message', (msg) => {
      let emailContent = '';
      let fromAddress = '';
      let headers = '';

      msg.on('body', (stream, info) => {
        if (info.which === 'HEADER.FIELDS (FROM TO SUBJECT DATE MESSAGE-ID)') {
          stream.on('data', (chunk) => {
            headers += chunk.toString('utf8');
          });
        } else {
          stream.on('data', (chunk) => {
            emailContent += chunk.toString('utf8');
          });
        }
      });

      let attrs: any;
      msg.once('attributes', (msgAttrs) => {
        attrs = msgAttrs;
        console.log('Message attributes:', JSON.stringify(attrs, null, 2));
        
        // Try multiple ways to extract sender email
        if (attrs.envelope && attrs.envelope.from && attrs.envelope.from.length > 0) {
          fromAddress = attrs.envelope.from[0].address;
          console.log('Extracted from envelope.from:', fromAddress);
        } else if (attrs.envelope && attrs.envelope.sender && attrs.envelope.sender.length > 0) {
          fromAddress = attrs.envelope.sender[0].address;
          console.log('Extracted from envelope.sender:', fromAddress);
        } else if (attrs.envelope && attrs.envelope.replyTo && attrs.envelope.replyTo.length > 0) {
          fromAddress = attrs.envelope.replyTo[0].address;
          console.log('Extracted from envelope.replyTo:', fromAddress);
        } else {
          console.log('No envelope data found, will parse from headers');
        }
      });

      msg.once('end', () => {
        // If we couldn't get fromAddress from envelope, try parsing headers
        if (!fromAddress || fromAddress === 'unknown') {
          console.log('Headers received:', headers);
          const fromMatch = headers.match(/From:\s*.*?([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/i);
          if (fromMatch && fromMatch[1]) {
            fromAddress = fromMatch[1];
            console.log('Extracted from headers:', fromAddress);
          } else {
            fromAddress = 'unknown';
            console.log('Could not extract email from headers either');
          }
        }
        
        console.log('Final fromAddress:', fromAddress);
        
        // Get message ID for duplicate prevention
        const messageId = attrs?.uid?.toString() || undefined;
        
        // Process the email for load requests
        processIncomingEmail(emailContent, fromAddress, messageId).catch(error => {
          console.error('Error processing email:', error);
        });
      });
    });

    fetch.once('error', (err) => {
      console.error('Fetch error:', err);
    });
  });
}

export function stopEmailMonitoring() {
  if (imapClient) {
    imapClient.end();
  }
}
